### ISSUE TITLE
Web Environment Integrity FYI And Review

### ISSUE THREAD

**Issue by RupertBenWiser** [WebView-CG/explainers#4]
A bunch of us from Google have published an explainer for [Web Environment Integrity](https://github.com/RupertBenWiser/Web-Environment-Integrity/blob/main/explainer.md).

The goal is to provide attestation signals for the web environment to help with anti-fraud use cases. There are additional WebView considerations so we're looking forward to reviews and feedback from the WebView CG. Please open any discussion under the [Github issues](https://github.com/RupertBenWiser/Web-Environment-Integrity/issues).

Looking forward to hearing back from you all!

**Comment by A1kmm** [comment]
Apparently it is locked down and isn't allowing either issues or PRs - so if you aren't getting a lot of feedback it might be more that your settings are not allowing it rather than that there is no feedback.

I've created a detailed explanation of one potential risk this could raise around tracking, and provided some ideas for implementers - GitHub won't let me create it as a PR: https://github.com/RupertBenWiser/Web-Environment-Integrity/compare/main...A1kmm:Web-Environment-Integrity:patch-1

I also think there are legitimate questions of whether or not the tension between security and privacy actually have a sweet spot where it is acceptable with this approach. Let's assume the legitimate anti-fraud use for this is to make it expensive for one person to create a million accounts on a site without the site operator figuring it out (with corollaries like "once you're banned, you stay banned until the site operator says otherwise"). That is a legitimate goal, but to do that based on consent free device attestation (i.e. the user doesn't normally decide individually whether to make an attestation) requires privacy controls, that undermine the anti-fraud usage of it. If I, as a user, can create 1,000,000 partitions for the same site on one device, has this specification really served the legitimate anti-fraud purpose? If I can't create different partitions as often as I might clear cookies or restart Private Browsing mode for a site, then it has privacy implications.

There is also a lack of clarity as to what it is proposed attesters would attest to, and I think while it might depend, to establish the use case for this clearly, providing some examples is necessary. The words "the modified browser can still request Web Environment Integrity attestation" are particularly unclear - is it saying that someone, given enough money, can fork a browser and put in a request to the attester on the platform on which they want it to run, and if they are a sufficiently, recognised company, the attester might agree to issue attestations for browsers signed by them. Or is it saying that in practice, attesters will not make signature verification of the browser a requirement to create attestations? I think the lack of trust Google is seeing on this is probably because Google does in fact have a track record of gating features and not allowing anyone not big enough to play control. For example, to implement a web browser with Chrome equivalent WebAuthn on Android, you need access to https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/Fido2PrivilegedApiClient, and as I understand it, Google only lets apps signed by big browser vendors have access to it, not people customising their own browsers. If "request attestation" means "you can ask, but we'll probably say no", or the attestation will mention that it is a 'non-standard' browser, that sites will routinely deny, this doesn't seem that compatible with an Open Web. Similarly, an Open Web would allow people to run their own Operating System - I think there is low trust there because Google has been making it difficult, for example, to use services like Google Pay on operating systems like LineageOS, using similar attestation schemes, and it is not clear from the explainer if this would, for example, mean LineageOS users are suddenly cut off from most of the web (which again, is not compatible with the idea of an Open Web).

Perhaps a better way to achieve the same goals around anti-fraud, without the same privacy and Open Web concerns, would be to promote world-wide PKI coupled with a zero-knowledge proof scheme that generates a unique token per identity and site.

Imagine if every individual in the world could authenticate to an identity provider (ideally provided by their government, but an interim solution could be a private sector version for countries where the government doesn't provide it), using a smartcard / token, and get a certificate from the provider saying that the holder of the private key is authenticated between two times (relatively close together), and a unique identifier for the person. Worldwide PKI to assign everyone a secret unique identifier to a private key they control is the hardest part of the problem, and it is hard for political rather than technical reason primarily - so if companies like Google could solve that (pending governments catching up).

Now imagine a zk-SNARK (zero knowledge succinct non-interactive argument of knowledge) network that takes as public inputs a website identifier w, a userhash u and a time t, and as private inputs a government certificate c, and a private key p. The browser uses the network to create an argument of knowledge that u = H(w, c.userid) (for some HMAC H), that p corresponds to the public key in c, and that c is signed by one of a set of authorised signers, and c.not_before <= t <= c.not_after. Note that c.userid must be a secret - high entropy and not disclosed to anyone else, otherwise it is possible for someone to mass compute `H(w, userid)` for all known userids, and hence deanonymise the user.

Now the web browser submits the zk-SNARK to the server. The server validates it, and checks that the user hash has not been seen before. The user hash is different for different sites, but for the same site, it would always be the same.

Note that providing a per-site unique (to a person) token would be a big decision - it should not be done without  explicit consent of the person. But if those are the terms of usage of the site, that is not that unreasonable. The 'site identifier' could also include a number (and the site could set rules, e.g. the number must be between 1-10) if the intent is to allow one person to have at most 10 accounts, and for the site not to be able to determine which of those 10 are the same person - while stopping them from having, say, 1,000,000 accounts.

Notable differences to WEI are:
* It would work with entirely Open Source software, that the user is free to change at will, as long as it implements the protocol correctly (the only potential exception is limited to the smartcard / token used to authorise - everything else can be open).
* It provides cryptographic guarantees rather than relying on the behaviour of anyone doing attestation.
* It limits the number of roles involved in the process.
* It doesn't require any expensive equipment beyond a way to authenticate users - this could be implemented entirely in software and roll out a lot more quickly than a solution that requires chain of trust from CPU boot on.
* It verifies the person rather than the device, so cannot be worked around by buying a lot of devices.
